schema_version: 1

context:
  name: de-zoll
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/de-zoll-${{ version }}.tar.gz
  sha256: f64515c9d544235e2bb30116999d002ef9b847f14f96a24c1bdb06604e66684f

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - poetry
  run:
    - python >=${{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

tests:
  - python:
      imports:
        - deutschland.zoll
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Einfuhrzoll API
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/bundesAPI/zoll-api

extra:
  recipe-maintainers:
    - jan-janssen
